services:
  webserver:
    container_name: nginx_server
    image: 'nginx:1.25-alpine3.18'
    working_dir: /www
    volumes:
      - './HandleStock:/www/HandleStock'
      - './DockerFile/nginx/nginx.conf:etc/nginx/conf.d/default.conf'
    ports:
      - '8080:80'

  postgres:
    container_name: DB_CI_Docker_symfony
    image: 'postgres:17-alpine3.21'
    environment:
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
      - POSTGRES_DB={POSTGRES_DB}
    volumes:
      - './postgres:/var/lib/postgres/data'
    ports:
      - '5432:5432'

  php_container:
    container_name: symfony_container
    build: ./Docker_files/Dockerfile
    working_dir: /www/HandleStock
    volumes:
      - './HandleStock:/www/HandleStock'
